export const alunosFake = [
	{
		id: 1,
		personal_id: 1,
		nome: "Carlos",
		sobrenome: "Silva",
		email: "carlos@gmail.com",
		telefone: "83999911111",
		inicio_plano: "2026-02-01",
		inicio_cadastro: "2026-01-20",
		plano_id: 1,
	},
	{
		id: 2,
		personal_id: 1,
		nome: "Mariana",
		sobrenome: "Souza",
		email: "mariana@gmail.com",
		telefone: "83999922222",
		inicio_plano: "2026-02-10",
		inicio_cadastro: "2026-01-25",
		plano_id: 2,
	},
	{
		id: 3,
		personal_id: 1,
		nome: "Lucas",
		sobrenome: "Pereira",
		email: "lucas@gmail.com",
		telefone: "83999933333",
		inicio_plano: "2026-03-01",
		inicio_cadastro: "2026-02-01",
		plano_id: 1,
	},
	{
		id: 4,
		personal_id: 2,
		nome: "Ana",
		sobrenome: "Costa",
		email: "ana@gmail.com",
		telefone: "83999944444",
		inicio_plano: "2026-03-05",
		inicio_cadastro: "2026-02-10",
		plano_id: 2,
	},
	{
		id: 5,
		personal_id: 2,
		nome: "Rafael",
		sobrenome: "Lima",
		email: "rafael@gmail.com",
		telefone: "83999955555",
		inicio_plano: "2026-03-10",
		inicio_cadastro: "2026-02-15",
		plano_id: 1,
	},
	{
		id: 6,
		personal_id: 1,
		nome: "Beatriz",
		sobrenome: "Almeida",
		email: "beatriz@gmail.com",
		telefone: "83999966666",
		inicio_plano: "2026-02-15",
		inicio_cadastro: "2026-01-30",
		plano_id: 3,
	},
	{
		id: 7,
		personal_id: 1,
		nome: "Felipe",
		sobrenome: "Ferreira",
		email: "felipe@gmail.com",
		telefone: "83999977777",
		inicio_plano: "2026-02-20",
		inicio_cadastro: "2026-02-01",
		plano_id: 2,
	},
	{
		id: 8,
		personal_id: 2,
		nome: "Juliana",
		sobrenome: "Rocha",
		email: "juliana@gmail.com",
		telefone: "83999988888",
		inicio_plano: "2026-03-12",
		inicio_cadastro: "2026-02-18",
		plano_id: 3,
	},
	{
		id: 9,
		personal_id: 2,
		nome: "Gustavo",
		sobrenome: "Mendes",
		email: "gustavo@gmail.com",
		telefone: "83999999999",
		inicio_plano: "2026-03-15",
		inicio_cadastro: "2026-02-20",
		plano_id: 1,
	},
	{
		id: 10,
		personal_id: 1,
		nome: "Camila",
		sobrenome: "Teixeira",
		email: "camila@gmail.com",
		telefone: "83999888888",
		inicio_plano: "2026-02-25",
		inicio_cadastro: "2026-02-05",
		plano_id: 2,
	},
	{
		id: 11,
		personal_id: 1,
		nome: "Ricardo",
		sobrenome: "Cardoso",
		email: "ricardo@gmail.com",
		telefone: "83999877777",
		inicio_plano: "2026-03-01",
		inicio_cadastro: "2026-02-10",
		plano_id: 3,
	},
	{
		id: 12,
		personal_id: 2,
		nome: "Sabrina",
		sobrenome: "Moura",
		email: "sabrina@gmail.com",
		telefone: "83999866666",
		inicio_plano: "2026-03-05",
		inicio_cadastro: "2026-02-12",
		plano_id: 2,
	},
	{
		id: 13,
		personal_id: 2,
		nome: "Thiago",
		sobrenome: "Ribeiro",
		email: "thiago@gmail.com",
		telefone: "83999855555",
		inicio_plano: "2026-03-08",
		inicio_cadastro: "2026-02-15",
		plano_id: 1,
	},
	{
		id: 14,
		personal_id: 1,
		nome: "Patrícia",
		sobrenome: "Barbosa",
		email: "patricia@gmail.com",
		telefone: "83999844444",
		inicio_plano: "2026-03-10",
		inicio_cadastro: "2026-02-18",
		plano_id: 2,
	},
	{
		id: 15,
		personal_id: 2,
		nome: "Vinícius",
		sobrenome: "Santos",
		email: "vinicius@gmail.com",
		telefone: "83999833333",
		inicio_plano: "2026-03-12",
		inicio_cadastro: "2026-02-20",
		plano_id: 3,
	},
];

export const planosFake = [
	{ id: 1, nome: "Plano Básico", preco: 120 },
	{ id: 2, nome: "Plano Intermediário", preco: 180 },
	{ id: 3, nome: "Plano Ultra", preco: 350 },
];

export const programasTreino = [
	{
		id: 1,
		nome: "Cardio",
		descricao:
			"Treinos focados em resistência e queima calórica, melhora do condicionamento físico e fortalecimento do sistema cardiovascular.",
		duracao: 40,
		categoria: "cardio",
	},
	{
		id: 2,
		nome: "PowerLift",
		descricao:
			"Programa de alta intensidade voltado para ganho de força e performance. Ideal para quem busca evolução em cargas.",
		duracao: 60,
		categoria: "forca",
	},
	{
		id: 3,
		nome: "Calistenia",
		descricao:
			"Treinamento com o peso do próprio corpo que desenvolve força, equilíbrio e controle corporal.",
		duracao: 45,
		categoria: "funcional",
	},
	{
		id: 4,
		nome: "Musculação",
		descricao:
			"Treinos personalizados para hipertrofia, definição ou resistência muscular.",
		duracao: 70,
		categoria: "musculacao",
	},
	{
		id: 5,
		nome: "Yoga",
		descricao:
			"Aulas voltadas para equilíbrio, flexibilidade e conexão mente-corpo.",
		duracao: 50,
		categoria: "mobilidade",
	},
	{
		id: 6,
		nome: "Pilates",
		descricao:
			"Fortalecimento do core, melhora da postura e prevenção de lesões.",
		duracao: 50,
		categoria: "mobilidade",
	},
	{
		id: 7,
		nome: "HIIT",
		descricao:
			"Treino intervalado de alta intensidade para queima rápida de gordura.",
		duracao: 30,
		categoria: "cardio",
	},
	{
		id: 8,
		nome: "Treino Funcional",
		descricao:
			"Exercícios que trabalham múltiplos grupos musculares com movimentos naturais.",
		duracao: 45,
		categoria: "funcional",
	},
	{
		id: 9,
		nome: "Core Training",
		descricao:
			"Treino focado no fortalecimento do abdômen e lombar para estabilidade corporal.",
		duracao: 35,
		categoria: "core",
	},
	{
		id: 10,
		nome: "Mobilidade",
		descricao:
			"Treinos voltados para melhorar amplitude de movimento e prevenir lesões.",
		duracao: 30,
		categoria: "mobilidade",
	},
];

export const agendamentos = [
	{
		id: 1,
		alunoId: 3,
		nomeAluno: "João",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "08:00",
		fim: "09:00",
		servico: "Treino Personal",
		status: "confirmado",
	},
	{
		id: 2,
		alunoId: 5,
		nomeAluno: "Maria",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "10:00",
		fim: "11:00",
		servico: "Aula em grupo",
		status: "pendente",
	},
	{
		id: 3,
		alunoId: 5,
		nomeAluno: "Maria",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "10:00",
		fim: "11:00",
		servico: "Aula em grupo",
		status: "pendente",
	},
	{
		id: 4,
		alunoId: 5,
		nomeAluno: "Maria",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "10:00",
		fim: "11:00",
		servico: "Aula em grupo",
		status: "pendente",
	},
	{
		id: 5,
		alunoId: 5,
		nomeAluno: "Maria",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "10:00",
		fim: "11:00",
		servico: "Aula em grupo",
		status: "cancelado",
	},
	{
		id: 6,
		alunoId: 5,
		nomeAluno: "Maria",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "10:00",
		fim: "11:00",
		servico: "Aula em grupo",
		status: "pendente",
	},
	{
		id: 7,
		alunoId: 5,
		nomeAluno: "Maria",
		personalId: 1,
		nomePersonal: "Carlos",
		data: "2026-03-13",
		inicio: "10:00",
		fim: "11:00",
		servico: "Aula em grupo",
		status: "cancelado",
	},
];

export const pagamentos = [
	{
		id: 1,
		nome: "João",
		plano: "Plano Premium",
		valor: "R$150,00",
		data: "12/03/2026",
		status: "Pago",
	},
	{
		id: 2,
		nome: "Maria",
		plano: "Plano Básico",
		valor: "R$120,00",
		data: "13/03/2026",
		status: "Pendente",
	},
	{
		id: 3,
		nome: "Carlos",
		plano: "Plano Funcional",
		valor: "R$200,00",
		data: "10/03/2026",
		status: "Pago",
	},
	{
		id: 1,
		nome: "João",
		plano: "Plano Premium",
		valor: "R$150,00",
		data: "12/03/2026",
		status: "Pago",
	},
	{
		id: 2,
		nome: "Maria",
		plano: "Plano Básico",
		valor: "R$120,00",
		data: "13/03/2026",
		status: "Pendente",
	},
	{
		id: 3,
		nome: "Carlos",
		plano: "Plano Funcional",
		valor: "R$200,00",
		data: "10/03/2026",
		status: "Pago",
	},
	{
		id: 1,
		nome: "João",
		plano: "Plano Premium",
		valor: "R$150,00",
		data: "12/03/2026",
		status: "Pago",
	},
	{
		id: 2,
		nome: "Maria",
		plano: "Plano Básico",
		valor: "R$120,00",
		data: "13/03/2026",
		status: "Pendente",
	},
	{
		id: 3,
		nome: "Carlos",
		plano: "Plano Funcional",
		valor: "R$200,00",
		data: "10/03/2026",
		status: "Pago",
	},
	{
		id: 1,
		nome: "João",
		plano: "Plano Premium",
		valor: "R$150,00",
		data: "12/03/2026",
		status: "Pago",
	},
	{
		id: 2,
		nome: "Maria",
		plano: "Plano Básico",
		valor: "R$120,00",
		data: "13/03/2026",
		status: "Pendente",
	},
	{
		id: 3,
		nome: "Carlos",
		plano: "Plano Funcional",
		valor: "R$200,00",
		data: "10/03/2026",
		status: "Pago",
	},
	{
		id: 1,
		nome: "João",
		plano: "Plano Premium",
		valor: "R$150,00",
		data: "12/03/2026",
		status: "Pago",
	},
	{
		id: 2,
		nome: "Maria",
		plano: "Plano Básico",
		valor: "R$120,00",
		data: "13/03/2026",
		status: "Pendente",
	},
	{
		id: 3,
		nome: "Carlos",
		plano: "Plano Funcional",
		valor: "R$200,00",
		data: "10/03/2026",
		status: "Pago",
	},
];

export const notifications = [
	"Nova mensagem de João",
	"Treino atualizado",
	"Pagamento recebido",
	"Treino atualizado",
	"Pagamento recebido",
	"Treino atualizado",
	"Pagamento recebido",
];

export const personais = [
	{
		id: 1,
		name: "João",
		role: "Desenvolvedor Front-End",
		whatsapp: "#",
		instagram: "#",
		twitter: "#",
		image: "caminho/para/imagem.jpg",
	},
	{
		id: 2,
		name: "Maria ",
		role: "Designer",
		whatsapp: "#",
		instagram: "#",
		twitter: "#",
		image: "caminho/para/imagem2.jpg",
	}
];
